f = open('test.txt', 'w')
f.write('hello python,i am here!')
f.close()
f = open('test.txt', 'a')
f.write('hello')
# f = open('test.txt')
# content = f.read(10)
# print(content)
# print('-' * 30)
# content = f.read()
# print(content)
# f.close()
